---
name: action-pdk-validate-test
description: Uses bundle exec to run pdk validate and test
    required: false
branding:
  icon: check-square
  color: orange
runs:
  using: docker
  image: Dockerfile
